### PR TITLE
fixed "gdpr [v9] compatible css"

### PR DESCRIPTION
**Pull request by Hmone23**
This PR fixes for some css classes that aren't working in [v9].

### CODE REVIEW

**Comment by hissy** [comment]
Who can review this PR? @mlocati @mnakalay

**Comment by hissy** [comment]
@mlocati @mnakalay Any updates?

**Comment by mlocati** [comment]
@hissy I gave you admin access to this repository

**Comment by hissy** [comment]
@mlocati 

Thanks, but how can I upload the package to the marketplace? Do we have a shared account to manage community maintenance packages?

**Comment by mlocati** [comment]
@hissy I think you should ask Franz or Korvin about that: at the moment those packages can only be published by a3020, but he told me it's fine to takeover his packages

**Comment by mnakalay** [comment]
Actually I should also be able to upload it to a3020 account as long as he said it was ok

**Comment by hissy** [comment]
I don't prefer to use a3020 account because users will confuse when another guy actually maintains the package.
I prefer to create a shared account for this GitHub organization.

**Comment by mlocati** [comment]
That's a nice idea

**Pull request merged**
